export const facultyMembersData: FacultyMember[] = [
  {
    name: "Sebastian Jaimungal",
    title: "Professor and Department Chair",
    image: "/utstat-math-finance/assets/members/SebastianJaimungal.jpg",
    imagePosition: "62% center",
    imageScale: 1.55,
    imageTransformOrigin: "center 28%",
    bio: "Stochastic control and games, reinforcement learning, machine learning, clean energy, and algorithmic trading and other applications in mathematical finance.",
    links: {
      email: "sebastian.jaimungal@utoronto.ca",
      website: "https://sebastian.statistics.utoronto.ca/",
      googleScholar: "https://scholar.google.com/citations?user=-ggKCCAAAAAJ",
      linkedin: "https://ca.linkedin.com/in/sebastian-jaimungal-0353585",
    },
  },
  {
    name: "Ting-Kam Leonard Wong",
    title: "Associate Professor",
    image: "/utstat-math-finance/assets/members/LeonardWong.jpg",
    imagePosition: "center top",
    bio: "Portfolio theory, optimal transport, information geometry, stochastic processes, statistical methodology, probability, and mathematical finance.",
    links: {
      email: "tkl.wong@utoronto.ca",
      website: "https://tkl-wong.github.io/",
      googleScholar: "https://scholar.google.com/citations?user=0CSf_Z8AAAAJ&hl=en",
      linkedin: "https://ca.linkedin.com/in/leonard-wong-a4093561",
    },
  },
  {
    name: "Silvana Pesenti",
    title: "Associate Professor",
    image: "/utstat-math-finance/assets/members/SilvanaPesenti.jpg",
    imagePosition: "center top",
    bio: "Actuarial science, quantitative risk management, risk measures, dependence uncertainty, stress testing, systemic risk, and insurance.",
    links: {
      email: "silvana.pesenti@utoronto.ca",
      website: "https://pesenti.utstat.utoronto.ca/",
      googleScholar: "https://scholar.google.com/citations?user=-75b0qUAAAAJ&hl=en",
      linkedin: "https://ca.linkedin.com/in/silvanapesenti",
    },
  },
  {
    name: "Dena Firoozi",
    title: "Assistant Professor",
    image: "https://denafiroozi.github.io/DF/images/profile.png",
    imagePosition: "center top",
    bio: "Mean-field games, stochastic control, stochastic analysis, systemic risk, risk-sensitive decision-making, and applications in finance.",
    links: {
      email: "dena.firoozi@hec.ca",
      website: "https://denafiroozi.github.io/DF/",
      googleScholar: "https://scholar.google.com/citations?user=weHKFEYAAAAJ&hl=en",
      linkedin: "https://ca.linkedin.com/in/dena-firoozi-83795135",
    }
  },
  {
    name: "Xiaofei Shi",
    title: "Assistant Professor",
    image: "/utstat-math-finance/assets/members/XiaofeiShi.jpg",
    imagePosition: "center 5%",
    bio: "Stochastic optimization, stochastic differential equations, portfolio theory, transaction costs, machine learning, statistical methodology, and applications to mathematical finance.",
    links: {
      email: "xf.shi@utoronto.ca",
      website: "https://xf-shi.github.io/",
      googleScholar: "https://scholar.google.com/citations?user=83XDxwUAAAAJ&hl=en",
      linkedin: "https://ca.linkedin.com/in/xiaofei-shi-41808b273",
    },
  },
  {
    name: "Christopher Blier-Wong",
    title: "Assistant Professor",
    image: "/utstat-math-finance/assets/members/ChristopherBlierWong.jpg",
    imagePosition: "center top",
    bio: "Actuarial science, quantitative risk management, dependence modelling, risk sharing, decision theory, statistical methodology, and machine learning in insurance.",
    links: {
      email: "christopher.blierwong@utoronto.ca",
      website: "https://chrisbw.ca/research/",
      googleScholar: "https://scholar.google.com/citations?user=st1DkB8AAAAJ&hl=en",
      linkedin: "https://ca.linkedin.com/in/christopher-blier-wong",
    },
  },
];
