export const facultyStudentsData: FacultyMember[] = [
  {
    name: "Qinghua Ren",
    title: "Postdoctoral researcher (Silvana Pesenti)",
    since: 2026,
    image: "",
    bio: "",
    links: {
      email: "qinghua.ren@utoronto.ca",
      website: "https://qinghua-ren.github.io/",
    },
  },
  {
    name: "Vedant Choudhary",
    title: "PhD student (Sebastian Jaimungal)",
    since: 2021,
    image: "https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=QF2q72kAAAAJ&citpid=1",
    bio: "Generative modelling of financial time series data.",
    links: {
      email: "vedant.choudhary@mail.utoronto.ca",
      googleScholar: "https://scholar.google.ca/citations?user=QF2q72kAAAAJ&hl=en",
      linkedin: "https://ca.linkedin.com/in/vedantch",
    },
  },
  {
    name: "Kathleen Miao",
    title: "PhD student (Silvana Pesenti)",
    since: 2021,
    image: "",
    bio: "Mathematical problems in insurance and risk management, dependence uncertainty, and robustness.",
    links: {
      email: "k.miao@mail.utoronto.ca",
      website: "https://www.kathleenmiao.ca/",
      googleScholar: "https://scholar.google.ca/citations?user=1iTfxR4AAAAJ&hl=en",
      linkedin: "https://www.linkedin.com/in/kathleen-m-7ba9411b5/",
    },
  },
  {
    name: "Brandon Tam",
    title: "PhD student (Silvana Pesenti)",
    since: 2023,
    image: "https://brandon-tam.github.io//images/Convocation%20-%20Individual%20Photo.jpg",
    bio: "Multivariate uncertainty sets and distributionally robust optimization.",
    links: {
      email: "brandontam.tam@mail.utoronto.ca",
      website: "https://brandon-tam.github.io/",
      googleScholar: "https://scholar.google.ca/citations?user=lag1zpMAAAAJ&hl=en",
      linkedin: "https://www.linkedin.com/in/brandon-tam-b459861b6",
    },
  },
  {
    name: "Elijah French",
    title: "PhD student (Sebastian Jaimungal & Leonard Wong)",
    since: 2024,
    image: "",
    bio: "Mean-field games.",
    links: {
      email: "elijah.french@mail.utoronto.ca",
      website: "https://elijahfrench.com/",
      linkedin: "https://www.linkedin.com/in/elijah-french/",
    },
  },
  {
    name: "Mathew Cater",
    title: "PhD student (Sebastian Jaimungal)",
    since: 2024,
    image: "",
    bio: "",
    links: {
      linkedin: "https://ca.linkedin.com/in/mathew-cater-benavides",
    },
  },
  {
    name: "Brian Ceco",
    title: "PhD student (Leonard Wong & Xiaofei Shi)",
    since: 2024,
    image: "",
    bio: "",
    links: {
      website: "https://brianceco.wordpress.com/",
      linkedin: "https://ca.linkedin.com/in/brian-ceco",
    },
  },
  {
    name: "Radu Alexe Padina",
    title: "PhD student (Xiaofei Shi)",
    since: 2025,
    image: "",
    bio: "",
    links: {
      email: "radu.alexepadina@mail.utoronto.ca",
    },
  },
  {
    name: "Shang Li",
    title: "PhD student (Sebastian Jaimungal & Wenlong Mou)",
    since: 2025,
    image: "",
    bio: "",
    links: {},
  },
  {
    name: "Zhe Zhou",
    title: "PhD student (Dena Firoozi)",
    since: 2025,
    image: "",
    bio: "",
    links: {},
  },
  {
    name: "Denis Khatnyuk",
    title: "PhD student (Sebastian Jaimungal)",
    since: 2026,
    image: "",
    bio: "",
    links: {
      linkedin: "https://ca.linkedin.com/in/dkhatnyuk",
    },
  },
  {
    name: "Terrence Allder",
    title: "PhD student (Sebastian Jaimungal & Silvana Pesenti)",
    since: 2026,
    image: "",
    bio: "",
    links: {
      linkedin: "https://ca.linkedin.com/in/terrenceallder",
    },
  },
  {
    name: "Aiden Boyle",
    title: "PhD student (Sebastian Jaimungal & Dena Firoozi)",
    since: 2026,
    image: "",
    bio: "",
    links: {},
  },
  {
    name: "Isaac Marchand",
    title: "PhD student (Xiaofei Shi & Christopher Blier-Wong)",
    since: 2026,
    image: "",
    bio: "",
    links: {
      email: "isaac.marchand@mail.utoronto.ca",
    },
  },
];
